# Generated by Django 5.2.13 on 2026-05-01 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_reward_member_ids(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")

    for profile in UserProfile.objects.all():
        if profile.reward_member_id:
            continue

        while True:
            candidate = f"QB-{uuid.uuid4().hex[:8].upper()}"
            if not UserProfile.objects.filter(reward_member_id=candidate).exists():
                profile.reward_member_id = candidate
                profile.save(update_fields=["reward_member_id"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reward_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reward_member_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reward_preference',
            field=models.CharField(choices=[('bookstore', 'Book Reward'), ('cafe_discount', 'Cafe / Restaurant Discount'), ('study_cafe', 'Legacy Study Cafe'), ('gym_pool', 'Legacy Gym / Pool')], default='bookstore', max_length=30),
        ),
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_preference', models.CharField(max_length=30)),
                ('reward_level', models.PositiveIntegerField()),
                ('reward_title', models.CharField(max_length=255)),
                ('partner_name', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'reward_preference', 'reward_level'), name='unique_reward_claim_per_user_preference_level')],
            },
        ),
        migrations.RunPython(backfill_reward_member_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='reward_member_id',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
