# Generated by Django 5.2.13 on 2026-04-27 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('planned_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('ai_detected_category', models.CharField(choices=[('reading', 'Reading'), ('studying', 'Studying'), ('workout', 'Workout'), ('coding', 'Coding'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='other', max_length=20)),
                ('ai_detected_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme', 'Extreme')], default='easy', max_length=20)),
                ('ai_estimated_duration_minutes', models.PositiveIntegerField(default=15)),
                ('ai_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('ai_explanation', models.TextField(blank=True)),
                ('anomaly_flags', models.JSONField(blank=True, default=dict)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['planned_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_duration_minutes', models.PositiveIntegerField()),
                ('earned_xp', models.PositiveIntegerField()),
                ('xp_breakdown', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='tasks.task')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'planned_date'], name='tasks_task_user_id_b356a5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='tasks_task_user_id_c0fce1_idx'),
        ),
    ]
