# Generated by Codex on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_time_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="ai_detected_category",
            field=models.CharField(default="general", max_length=80),
        ),
    ]
