# Generated by Django 5.2.13 on 2026-04-27 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('reading', 'Reading'), ('studying', 'Studying'), ('workout', 'Workout'), ('coding', 'Coding'), ('cleaning', 'Cleaning'), ('other', 'Other')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme', 'Extreme')], max_length=20)),
                ('estimated_duration_minutes', models.PositiveIntegerField()),
                ('is_predefined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_predefined', 'category', 'title'],
                'indexes': [models.Index(fields=['is_predefined', 'category'], name='activities__is_pred_fb1fc9_idx'), models.Index(fields=['created_by'], name='activities__created_8db573_idx')],
            },
        ),
    ]
