# Generated by Codex on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="category",
            field=models.CharField(max_length=80),
        ),
    ]
